README.md, freecad.rb
Added support for v0.15 release and building latest FreeCAD HEAD
=> V0.15 support

Formula/freecad.rb, Formula/med-file.rb
- Apply Debian Arch Linux patches for hdf5 1.10 compatibility
- Apply Python bindings patches
Fixes homebrew-freecad#16
=> Import med-file from Homebrew/science

Formula/freecad.rb
=> Add CLOUD module as a build option and Remove qt4 test

Formula/coin.rb, Formula/matplotlib.rb, Formula/med-file.rb, Formula/nglib.rb, Formula/opencamlib.rb, Formula/pivy.rb, Formula/pyside2-tools.rb, Formula/pyside2.rb, Formula/shiboken2.rb
=> Add bottles to test if we can re-enable travis build on MacOS

Formula/freecad.rb
=> Update freecad formula to get pre-compiled version from bottle

Formula/freecad.rb
=> Fix patching of opencascade

Formula/freecad.rb
should be boost-python3 for python3
=> update to boost-python3

Formula/freecad.rb, Formula/matplotlib.rb
with homebrew config, xcode 12 / MacOS BigSur and matplotlib installation. 
Update VTK8.2 cmake path, add a few dependencies
=> Update build formula to fix python detection

Formula/freecad.rb
The git number correspond to the 19pre which has been tagged
=> Build from original github repository - it is stable enough now ;)

Formula/freecad.rb
=> Update formula checksum following recompilation

Formula/freecad.rb
=> Add opencamlib as a dependecy

Formula/freecad.rb
=> Add build macOS App support

Formula/freecad.rb
add empty line between method defs, and some other minor cleanup
=> add empty line between method defs

Formula/freecad.rb
=> Fix build with latest boost (1.75)

Formula/freecad.rb, Formula/matplotlib.rb, Formula/nglib.rb, Formula/pyside2-tools.rb, Formula/pyside2.rb, Formula/shiboken2.rb
=> Update bottle for Catalina as to work with new boost version and fix nglib issue with OpenCascade 7.5.0

Formula/freecad.rb
=> remove boost v1.73 patches, as their not req for boost v1.74 or v1.75

Formula/boost-python3@1.75.0.rb, Formula/boost@1.75.0.rb, Formula/coin@4.0.0.rb, Formula/cython@0.29.21.rb, Formula/freecad.rb, Formula/icu4c@67.1.rb, Formula/matplotlib.rb, Formula/med-file.rb, Formula/nglib.rb, Formula/numpy@1.19.4.rb, Formula/opencamlib.rb, Formula/opencascade@7.5.0.rb, Formula/pivy.rb, Formula/pyqt@5.15.2.rb, Formula/pyside2-tools.rb, Formula/pyside2.rb, Formula/python3.9.rb, Formula/qt5152.rb, Formula/shiboken2.rb, Formula/sip@4.19.24.rb, Formula/swig@4.0.2.rb, Formula/tbb@2020_u3.rb, Formula/vtk@8.2.0.rb
=> Major update to break library dependencies

Formula/matplotlib.rb
=> Fix build on catalina

Formula/nglib.rb
=> Update nglib formula as to work with Catalina and bigsur

Formula/boost-python3@1.75.0.rb, Formula/boost@1.75.0.rb, Formula/coin@4.0.0.rb, Formula/cython@0.29.21.rb, Formula/freecad.rb, Formula/icu4c@67.1.rb, Formula/matplotlib.rb, Formula/med-file.rb, Formula/nglib.rb, Formula/numpy@1.19.4.rb, Formula/opencamlib.rb, Formula/opencascade@7.5.0.rb, Formula/pivy.rb, Formula/pyqt@5.15.2.rb, Formula/pyside2-tools.rb, Formula/pyside2.rb, Formula/python3.9.rb, Formula/qt5152.rb, Formula/shiboken2.rb, Formula/sip@4.19.24.rb, Formula/swig@4.0.2.rb, Formula/tbb@2020_u3.rb, Formula/vtk@8.2.0.rb
=> Update for catalina

Formula/shiboken2.rb
i believe the URL i added better explains what the shiboken/shiboken2 package is and does.
=> update homepage url for shiboken2

Formula/freecad.rb
Signed-off-by: vejmarie <jmverdun3@gmail.com>
=> Fix versioning issue on python path package

Formula/boost-python3@1.75.0.rb, Formula/boost@1.75.0.rb, Formula/coin@4.0.0.rb, Formula/cython@0.29.21.rb, Formula/elmer.rb, Formula/freecad.rb, Formula/icu4c@67.1.rb, Formula/matplotlib.rb, Formula/med-file.rb, Formula/nglib.rb, Formula/numpy@1.19.4.rb, Formula/opencamlib.rb, Formula/opencascade@7.5.0.rb, Formula/pivy.rb, Formula/pyqt@5.15.2.rb, Formula/pyside2-tools.rb, Formula/pyside2.rb, Formula/python3.9.rb, Formula/qt5152.rb, Formula/qwtelmer.rb, Formula/shiboken2.rb, Formula/sip@4.19.24.rb, Formula/swig@4.0.2.rb, Formula/tbb@2020_u3.rb, Formula/vtk@8.2.0.rb
Signed-off-by: vejmarie <jmverdun3@gmail.com>
=> Fix style warning following brew update

Formula/boost-python3@1.75.0.rb, Formula/boost@1.75.0.rb
here are the updated URLs for the bost 1.75 library
=> update urls for boost 1.75 formula file

Formula/boost-python3@1.75.0.rb, Formula/freecad.rb, Formula/nglib.rb, Formula/qt5152.rb
What ever the HEAD version do not work. So we need this fix to compile on Apple silicon.
=> Fix build system issues on Apple silicon.

Formula/coin@4.0.0.rb
=> update sha256sum for coin bigsur bottle

Formula/coin@4.0.0.rb, Formula/nglib.rb, Formula/vtk@8.2.0.rb
=> update sha256sum for coin bottle file for macos catalina

Formula/pyside2.rb
=> update pyside2 formula to have a conflicts_with code block

.github/workflows/publish.yml, .github/workflows/tests.yml
…files, building & publishing bottles [no ci]
=> [no ci] checkin empty `.gitignore` and initial workflow files for bottling

Formula/cython@0.29.21.rb
merge to fix certain `brew test-bot` failures that would otherwise make ci checks fail.
=> #hotfix cython, [no ci] fix python dep

Formula/nglib@6.2.2104.rb
add a versioned formula of netgen using the upstream ie. homebrew-core version of opencascade
=> [no ci] nglib setup a versioned formula of nglib using upstream opencascade

audit_exceptions/flat_namespace_allowlist.json, formula_renames.json
**NA**
```
```
```
```
**NA**
```
```
--- …
=> [no ci] remove list of migrations, and update flat namespace list

tap_migrations.json
**NA**
```
```
```
```
**NA**
```
```
--- …
=> update tap migrations list

README.md
**NA** this commit should only update the README to reflect the current changes to the freecad formula
```
```
```
```
**NA** this commit should only update the README to reflect the current changes to the freecad formula
```
```
---
Not all PRs require passing these checks ie. adding `[no ci]` in the commit message will prevent the CI from running but PRs that change formula files generally should run through the CI checks that way new bottles are built and uploaded to the repository thus not having to build all formula from source but rather …
=> [no ci] update readme

patches/freecad-0.19.2-mac-app-bundling.patch
**NA**
```
```
```
```
**NA**
```
```
--- …
=> [no ci] update mac app bundling patch file

Aliases/pyside2@5.15
=> attempt to make brew test-bot pr pull happy [no ci]

README.md
**na**
```
```
```
```
**na**
```
```
--- …
=> update readme [no ci]

Formula/matplotlib@3.4.3.rb
set a deprecation date for matplotlib@3.4.3 formula
=> [no ci] set a deprecation date for matplotlib@3.4.3 formula

Formula/med-file@4.1.0.rb
=> [no ci] deprecate med-file@4.1.0

Formula/shiboken2@5.15.5.rb
=> shi2 changes

casks/freecad.rb
=> setup a cask for the 0.20 release of freecad

Formula/pyside2@5.15.5.rb
=> add pkg ref for pyside2@5.15.5 for mojave

Formula/freecad.rb
=> freecad update formula file for m1 and v0.20 release

patches/freecad-0.20.1-macos-10.15-sdk.patch, patches/freecad-0.20.1-macos-app-bundling.patch
=> checkin 2 patch files for the 0.20.1 release of freecad [no ci]

Aliases/freecad
=> freecad [no ci] update alias

Formula/freecad@0.20.1.rb
=> [no ci] freecad: update caveats

.github/workflows/tests.yml
=> Ipatch.ci.updates

casks/freecad.rb
=> [no ci] attempt to fix houdini style err 🤷‍♂️

.github/workflows/tests.yml
=> [no ci] attempt to fix syntax err

.github/workflows/validate_runner_status.yml
preliminary commit for validating the status of self-hosted runners.
=> [no ci] first attempt for validating self-hosted runners

.github/README.md, .github/workflows/validate_runner_status.yml
and a README for explaining the process
```
```
```
```
```
```
---
[lm1]: …
=> [no ci] create a workflow / gha for auto connecting self-hosted runners

.github/workflows/tests.yml, Formula/swig@4.1.1.rb, autoupdate_bottles.yml
=> Ci.updates

.github/workflows/tests.yml
=> ci updates [no ci]

.github/workflows/tests.yml
=> add documentation for `tests.yml` [no ci]

.github/workflows/tests.yml
=> [no ci] ci update, cleanup `tests.yml`

Formula/pyside2@5.15.5.rb
=> [no ci] hotfix for style err

Formula/pyside2@5.15.5.rb
=> fix pyside2@5.15.5 style error [no ci]

.github/workflows/tests.yml
=> [no ci] see tests.yml for exp

.github/workflows/tests.yml
=> [no ci] add missing backslash

Formula/pyside2@5.15.11.rb
=> pyside rm previous bottle block [no ci]

.github/workflows/tests.yml
=> ci update possible syntax error [no ci]

patches/freecad-0.20.1-libarea-cmake.patch, patches/freecad-0.20.1-py3.11-support.patch
=> [no ci] add 2x patches for freecad@0.20.1

Formula/opencamlib.rb
=> opencamlib rm old bottle block [no ci]

Formula/opencascade@7.5.3.rb
=> [no ci] opencascade@7.5.3 rm bottle block

Formula/nglib@6.2.2104.rb
=> [no ci] nglib rm old bottles

README.md
=> [no ci] update readme with link to repology check tut vid

README.md
=> [no ci] remove previous large file

README.md
=> [no ci] adjust url for video link

Formula/freecad@0.20.rb, Formula/opencascade@7.5.0.rb, Formula/opencascade@7.5.3.rb, Formula/opencascade@7.6.0.rb, Formula/tbb@2020_u3.rb
=> [no ci] fix audit exceptions

Formula/opencascade@7.5.3.rb, Formula/opencascade@7.6.0.rb
=> fix style exceptions

patches/freecad-0.20.2-e57-add-missing-include.patch, patches/freecad-0.20.2-occ-error.patch, patches/freecad-0.20.2-setup-python-cmake.patch
=> pull in patches for new freecad formula file

patches/freecad-0.20.2-cmake-find-hdf5.patch, patches/freecad-0.20.2-vtk-9.3.patch
=> freecad 0.20.2 patch files [no ci]

patches/freecad-0.20.2-cmake-find-xercesc.patch
=> freecad 0.20.2_py310 add patch file xercesc [no ci]

Aliases/freecad
=> [no ci] update freecad alias

Aliases/freecad
=> freecad@0.21.2_py310: update alias [no ci]

.gitignore, README.md
=> update logos with svgs and remove ref of build flag [no ci]

patches/freecad@0.21.2_py310-backport-occ-v7.8.patch
=> checkin patch file to support occ v7.8 for freecad 0.21.2 release

patches/freecad@0.21.2_py310-backport-occ-v7.8.patch
=> [no ci] attempt to fix occ v7.8 backport patch file

README.md
=> [no ci] readme updates

patches/freecad@0.21.2_py310-HEAD-toposhape.h-fix.patch
=> update patch file [no ci]

cmd/README.md
=> tap maintenace: scaffold out external commands dir [no ci]

Aliases/freecad, Aliases/med-file, Aliases/medfile
=> [no ci] update aliases to point to newer formula

.pre-commit-config.yaml
=> [no ci] scaffold out bare bones .pre-commit-config.yaml

.github/workflows/tests.yml
=> Hbfc tap maintenance

.github/workflows/tests.yml
=> [no ci] update tests.yml logic to resolve style error

.github/workflows/tests.yml, .github/workflows/validate_runner_status.yml
- **[no ci] update tests.yml logic to resolve style error**
- **[no ci] fix 2x syntax errors in tests.yml**
- **fix spelling errors in validate_runner_status.yml file [no ci]**
```
```
```
```
```
```
---
Not all PRs require passing these checks ie. adding `[no ci]` in the commit message will prevent the CI from running but PRs that change formula files generally should run through the CI checks that way new bottles are built and uploaded to the repository thus not having to build all formula from source but rather installing from a bottle …
=> hbfc tap maintenance [no ci]

.github/workflows/tests.yml
=> tshoot: github actions working with tokens

.github/workflows/tests.yml
=> tshoot: github tokens with workflows in actions

patches/freecad@0.21.2_py310-fix-opengl-glu.patch
=> [no ci] freecad@0.21.2_py310 checkin patch for opengl glu

Aliases/freecad
=> [no ci] update tap alias to point to the new release of freecad

Aliases/freecad
```shell
```
```
```
```shell
```
--- …
=> [no ci] update freecad repo alias to freecad@1.0.1_py312

Formula/pyside2@5.15.15_py312.rb
```shell
```
```
```
```shell
```
--- …
=> pyside2@5.15.15_py312: push back disable date [no ci]
