FreeCAD/homebrew-freecad

README.md

Mercurial doesn't come by default on OSX installs and the error message if it isn't installed isn't obvious at all

Update README to mention mercurial

---

Formula/freecad.rb
Formula/pyside2-tools.rb
Formula/pyside2.rb
Formula/shiboken2.rb

Adds support for pyside2, pyside2-tools, and shiboken2.
Bypasses the setup.py based build as it's problematic, and simply relies on the
(working) cmake based build.
fixes #58

Adds pyside2 formulas

---

Formula/soqt.rb

- Tip as of 1/27/2018.
- Remove --with-soqt option.  soqt is refactored into a
separate formula
Refs FreeCAD/homebrew-freecad#55

coin: upgrade to latest tip

---

Formula/matplotlib.rb

The sierra matplotlib [bottle](https://dl.bintray.com/freecad/bottles-freecad/:matplotlib-2.1.1.sierra.bottle.tar.gz) is broken at the moment. The signature of the downloaded archive doesn't match what's in the formula, besides the hosted archive is actually the source code, not the bottle.
Because of the problem stated above, brew bottle install fails, and when brew tries to compile, it only uses python3, not python2. This patch fixed this problem.

Fix matplotlib formula for the latest homebrew

---

Formula/med-file.rb

This is removing an error while opening the FeM module under Mojave and latest version of homebrew which is dependant of HDF5 1.10 instead of 1.8. Med 3.3.1 patch is no longer available on the internet and the brew built is broken.

Switch to Med 4.0.0 with homebrew built. T

---

Formula/freecad.rb

this PR fixes the freecad formula when building with `--HEAD` flag or `-s`, `--build-from-source` when running `brew install`.
---
for whatever it's worth, running `brew audit freecad` on this formula reports 76 problems. as this formula currently sits. 🤷‍♂️ i'll submit a few more discrete PR's to this formula as opposed to one monolithic PR.

fix: do not pin head to specific commit but rather point to HEAD

---

Formula/freecad.rb

this PR alphabetizes the formula dependencies thus when running `brew audit` it brings the total errors down to 53. it also sets the minimum macos version to 10.13, i've successfully built freecad on macos 10.13 and 10.14 so no reason to set the minimum to catalina when we do not need too.

fix: brew audit, sort deps alphabetically

---

Formula/freecad.rb

add _if guard_ for older macos versions to fix install on mojave & high sierra.
also fix syntax error with cmake args that was preventing any install from happening.
**sorry about that**

freecad formula, please merge URGENT!

---

Formula/boost-python3@1.75.0.rb
Formula/boost@1.75.0.rb
Formula/coin@4.0.0.rb
Formula/cython@0.29.21.rb
Formula/elmer.rb
Formula/freecad.rb
Formula/icu4c@67.1.rb
Formula/matplotlib.rb
Formula/med-file.rb
Formula/nglib.rb
Formula/numpy@1.19.4.rb
Formula/opencamlib.rb
Formula/opencascade@7.5.0.rb
Formula/pivy.rb
Formula/pyqt@5.15.2.rb
Formula/pyside2-tools.rb
Formula/pyside2.rb
Formula/python3.9.rb
Formula/qt5152.rb
Formula/qwtelmer.rb
Formula/shiboken2.rb
Formula/sip@4.19.24.rb
Formula/swig@4.0.2.rb
Formula/tbb@2020_u3.rb
Formula/vtk@8.2.0.rb

Add also Elmer as a Formula into FreeCAD repo. Elmer can be used as a CFD for the FeM module and doesn't have an integrated fomrula. It is dependant from OpenCascade and Qt, might make sense to extend our formula support to it.
Use justyour.parts server as a primary source for bottles. Bottles can be retrieve from it more easily than from bintray and this will be a temporary solution up to the time we find alternative.

Fix FreeCAD --head build 

---

Formula/freecad.rb

updated the freecad formula file to use the stable release _0.19.1_ when downloading and build from source. which if different from building HEAD.

set the stable version of freecad to the v0.19.1 source tar ball

---

Formula/freecad.rb

i added three local variables to the `freecad.rb` formula file to make things easier to test and update
```rb
python_exe
python_headers
prefix_paths
```
spreading the `prefix_paths` across multiple lines makes reading and editing the formula file **way** more manageable than the current human 🐛 centipad that is [currently](https://github.com/FreeCAD/homebrew-freecad/blob/4040596a7fb6e570041442899b3c5af36959fbc5/Formula/freecad.rb#L74)

setup three local variables within freecad.rb formula file

---

Formula/boost-python3@1.75.0.rb
Formula/coin@4.0.0.rb
Formula/matplotlib.rb
Formula/nglib.rb
Formula/pivy.rb
Formula/pyside2-tools.rb
Formula/pyside2.rb
Formula/qt5152.rb
Formula/shiboken2.rb
Formula/sip@4.19.24.rb
Formula/vtk@8.2.0.rb

this will be the first on several files changed in this tap in hopes of fixing the style errors for the formula contained within this repo.
i ran,
```
brew style $ghforks/homebrew-freecad/Formula/boost-python3@1.75.0.rb
```
there shouldn't be any issues with the style guide lines of the formula file now.
i also uninstalled and rebuilt the formula locally without any issues and the changes from this PR applied.
i selected the wrong branch from my development fork on the prior PR i sent. _my bad_

fix style errors for formula using `brew audit` in prep for setting up homebrew tap with github actions and workflows

---

Formula/nglib.rb

fix style errors for boost-python3@1.75.0 formula using `brew style`

---

Formula/nglib.rb
Formula/vtk@8.2.0.rb

#189 
this pr should fix the sha256sum mismatches when building vtk@8.2.0 from source.

#nglib, update bottle definition for big sur

---

.github/pull_request_template.md

[no ci] add a link to github docs regarding PR/issue templates

---

.github/workflows/tests.yml

remove `self-hosted-mojavevm` from list of gha runners [no ci]

---

audit_exceptions/flat_namespace_allowlist.json

the below formula checks are not applicable for this PR.
```
```
```
```
```
```
---
[lm1]: …

pullin homebrew-core audit exception file for flat namespaces [no ci]

---

audit_exceptions/flat_namespace_allowlist.json

```
```
```
```
```
```
**above checks are not applicable for this PR**
---
[lm1]: …

[no ci] allow freecad app bundle to use libs with flat namespaces

---

patches/0001-ipatch-use-gcc-11.patch

**NA**
```
```
```
```
**NA**
```
```
--- …

add patch for elmer to use gcc version 11

---

.github/workflows/tests.yml

**NA**
```
```
```
```
**NA**
```
```
--- …

[no ci] exp with reenabling self-hosted vmmojave gha runner

---

patches/freecad-0.19.2-mac-app-bundling.patch

**NA**
```
```
**output** from running above command should _output_ something similar to the below
```
```
**NA**
```
```
---
[lm1]: <https://docs.github.com/en/communities/using-templates-to-encourag …

[no ci] checkin freecad v0.19.2 patch for mac app bundling

---

.github/workflows/tests.yml

checks are **NA**
```
```
```
```
```
```
---
[lm1]: <https://docs.github.com/en/communities/using-templates-to-enc …

[no ci] exp with alt homebrew-core repo for mojave

---

.github/workflows/tests.yml

[no ci] exp with using sed to resolve style exception 🤞

---

.github/workflows/tests.yml

[no ci] use my fork of homebrew-core for mojave

---

.github/workflows/publish.yml

na
```
```
```
```
na
```
```
---
[lm1]: <https://docs.github.com/en/communities/using-templates-to-encourage-usefu …

exp with --no-autosquash for publish workflow

---

patches/0001-patch-sbknumpyarrayconverter.cpp-for-shiboken2-with-.patch

[no ci] exp with adding a patch for shiboken2 to work with numpy v1.23

---

patches/0001-patch-sbknumpyarrayconverter.cpp-for-shiboken2-with-.patch

[no ci] attempt to fix sbknumpyarrayconverter.cpp patch

---

patches/0001-patch-sbknumpyarrayconverter.cpp-for-shiboken2-with-.patch

attempt to fix sbknumpyarrayconverter.cpp patch

---

patches/libshiboken-numpy-1.23.compat.patch
patches/libshiboken2-python10-compat.patch

[no ci] checkin external patch files for shiboken2

---

Formula/elmer.rb
Formula/pyside2@5.15.5.rb
casks/freecad.rb

fix style errors to make test-bot happy for freecad.rb [no ci]

---

Formula/freecad.rb
Formula/pyside2@5.15.5.rb

freecad.rb update file to work with m1 and 0.20 release

---

Formula/freecad.rb

This reverts commit 2a3a3d94f8f48832d06d83122d7ed89bfaf8f167.
```
```
```
```
```
```
---
[lm1]: …

Revert "freecad update formula file for m1 and v0.20 release (#359)"

---

patches/0001-fix-mac-app-bundling-for-brew-install.patch

```
```
**NA**
```
```
```
```
**NA**
--- …

[no ci] checkin patch file to fix `brew install freecad --HEAD`

---

README.md

There is no --with-no-macos-app install flag. I removed this install flag and clarified the usage of --with-macos-app.

Clarify --with-macos-app install flag [no ci]

---

.github/workflows/tests.yml

[no ci] update order or build bottle cmds

---

.github/workflows/tests.yml

[no ci] fix ci logic error

---

.github/workflows/tests.yml

[no ci] attempt reset env var for ci

---

.github/workflows/tests.yml

[no ci] possible syntax err

---

.github/workflows/tests.yml

[no ci] syntax err

---

.github/workflows/tests.yml

[no ci] update cmd for building bottles

---

.github/workflows/tests.yml

[no ci] tshoot mojave bottling

---

Formula/swig@4.1.1.rb

[no ci] swig: manually add bottle block

---

.github/workflows/tests.yml

NA
```
```
```
```
NA
```
```
---
[lm1]: <https://docs.github.com/en/communities/using-templates-to-encourage-usefu …

[no ci] update tests.yml to remove deprecated cmds

---

.github/workflows/tests.yml

[no ci] attempt to fix ci workflow error

---

.github/workflows/tests.yml

[no ci] attempt to use specific branch instead of commit hash for cat

---

.github/workflows/tests.yml

update syntax for checking the runner name when building bottles

---

Formula/swig@4.1.1.rb

swig rm excess bottle block for catalina [no ci]

---

Formula/tbb@2020_u3.rb

fix style error for tbb@2020 formula [no ci]

---

.github/workflows/tests.yml

[no ci] exp with using github hosted macos-12 runner

---

.github/workflows/tests.yml

[no ci] add new gh hosted runners

---

.github/workflows/tests.yml

[no ci] update to use latest version of `actions/cache`

---

Formula/pyside2@5.15.5.rb

[no ci] attempt to fix style error, make rubocop happy pyside2@5.15.5

---

.github/workflows/tests.yml

[no ci] use `--keep-old` with test-bot to allow single bottle updates

---

Formula/elmer.rb

[no ci] elmer remove bottle block use std vtk

---

Formula/qwtelmer.rb

qwtelmer [no ci] remove old bottle artifacts

---

.github/workflows/tests.yml

[no ci] update available runners

---

.github/workflows/tests.yml
Formula/elmer.rb
Formula/freecad@0.20.rb
Formula/opencascade@7.5.3.rb
Formula/shiboken2@5.15.11.rb
Formula/shiboken2@5.15.11_py310.rb
Formula/shiboken2@5.15.5.rb

[no ci] disable macos-large runners & fix style exceptions

---

patches/freecad-0.20.2-sofcselectioncpp.patch

freecad@0.20.2_py310: SoFCSelection patch file [no ci]

---

patches/freecad-0.20.2-boost-v1.85-and-missing-includes.patch
patches/freecad-0.20.2-drivergmfcpp.patch

freecad@0.20.2_py310: 2 more patch files [no ci]

---

.github/workflows/tests.yml

[no ci] add github provided ubuntu runner for ci

---

.github/workflows/tests.yml

fix syntax error in ci yaml file [no ci]

---

Formula/pybind11_py310.rb

pybind11 style error [no ci]

---

.github/workflows/tests.yml

[no ci] logic error with tests.yml

---

.github/workflows/tests.yml

github ci, update tests.yml to wok with lhotari/action-upterm [no ci]

---

.github/workflows/publish.yml
.github/workflows/tests.yml

[no ci] update tests.yml and publish.yml workflows for github ci

---

patches/freecad@0.21.2_py310-boost-185-PreferencePackManager-cpp.patch

freecad@0.21.2_py310: checkin patch file for boost v1.85.0 [no ci]

---

Aliases/freecad

freecad@0.21.2_py310: fix broken alias [no ci]

---

.github/workflows/publish.yml
.github/workflows/tests.yml
.github/workflows/validate_runner_status.yml

attempt to resolve shellcheck linting warnings / erros with yaml files

---

Formula/freecad@0.21.2_py310.rb

freecad@0.21.2_py310: update ln method to use ln_s

---

patches/freecad@0.21.2_py310-HEAD-toposhape.h-fix.patch

freecad@0.20.2_py310: add patch file for toposhape.h [no ci]

---

patches/freecad@0.21.2_py310-backport-occ-v7.8.patch

[no ci] freecad@0.20.2_py310: backport occ v7.8 cmake for 0.21.2

---

patches/freecad@0.21.2_py310-boost-dep-errors.patch

checkin new patch file for boost build errors [no ci]

---

patches/pyside2@5.15.15_py312-python-v3.12-support.patch

```
```
```
```
```
```
**NA**
---
[lm1]: <https://docs.github.com/en/communities/using-templates-to-encourage-usef …

[no ci] checkin patch file for pyside2 to support python v3.12

---

.github/workflows/tests.yml

[no ci] use upterm fork

---

.github/workflows/tests.yml

[no ci] update tests.yml to work with latest macos runner image

---

patches/freecad@1.0.0_rc2_py312-fix-pyside-path-issue.patch

[no ci] checkin in patch file

---

.github/workflows/tests.yml

[no ci] use all 4 github hosted runners at the same time

---

patches/freecad@0.21.2_py310-backport-xercesc-tests-updates.patch

[no ci] checkin new patch file for freecad@0.21.2_py310

---

.github/workflows/tests.yml

[no ci] tshoot linux build error with github ci

---

.github/workflows/tests.yml

[no ci] update tests.yml to check for self-hosted runners

---

.github/workflows/tests.yml

Hbfc tap maintenance [no ci]

---

.github/workflows/tests.yml

tshoot: homebrew test-bot github CI [no ci]

---

.github/workflows/tests.yml

tshoot: setting env var for self-hosted runner

---

.github/workflows/tests.yml

[no ci] tshooting

---

.github/workflows/tests.yml

[no ci] tshooting gh tokens

---

.github/workflows/tests.yml

[no ci] tshooting gh tokens #2

---

.github/workflows/tests.yml

[no ci] exp with using a github app to make auth api requests

---

.github/workflows/tests.yml

[no ci] exp with using pull_request_target

---

.github/workflows/tests.yml

[no ci] cleanup tests.yml workflow file

---

.github/workflows/tests.yml

disable step in workflow [no ci]

---

.github/workflows/tests.yml

[no ci] let certain steps continue to run even if they fail

---

.github/workflows/tests.yml

[no ci] manually set env var for GITHUB_ENV based on RUNNER_NAME

---

.github/workflows/tests.yml

[no ci] attempt to avoid brew test-bot cleanup based on runner name

---

.github/workflows/tests.yml

[no ci] update tests.yml workflow to use new env vars in attempt to NOT remove installed formula for self-hosted runner

---

.github/workflows/tests.yml

tshoot: add condition to only run cleanup before on non self-hosted runner ie. github hosted [no ci]

---

.github/workflows/tests.yml

[no ci] update formatting and rm ref to github token logic from tests.yml

---

.rubocop.yml
patches/freecad@0.21.2_py310-hdf5-cmake-fix.patch

[no ci] checkin a basic .rubocop.yml file for basic linting and new patch for hdf5

---

patches/freecad@0.21.2_py310-hdf5-fix-cmake-reruns.patch

[no ci] freecad@0.21.2_py310 checkin new patch for hdf5

---

.github/workflows/tests.yml

hbfc tap maintenance, attempt to resolve issue in pr #675 [no ci]

---

.github/workflows/tests.yml

- **hbfc tap maintenance, attempt to resolve issue in pr #675 [no ci]**
- **hbfc tap maintenance, attempt to resolve issue in pr #675 [no ci]**
```
```
```
```
```
```
---
For …

hbfc tap maintenance

---

.github/pull_request_template.md

hbfc tap maintenance, attempt to resolve errors with pull_request_template.md file

---

patches/freecad@1.0.1_py312-fix-bld-with-occ-v79.patch

```shell
```
```
```
```shell
```
--- …

[no ci] checkin new patch file to fix 1.0.1 bld err with occ v7.9

---

.github/workflows/tests.yml

```shell
```
```
```
```shell
```
--- …

[no ci] attempt to fix the error mentioned in the comment for github PR #681

---

Formula/fc_bundle.rb
Formula/fc_bundle_py312.rb
Formula/fc_bundle_py312_qt6.rb
Formula/freecad@0.20.1.rb
Formula/freecad@0.20.2_py310.rb
Formula/freecad@0.20.rb
Formula/freecad@0.21.2_py310.rb
Formula/freecad@1.0.0_py312.rb
Formula/freecad@1.0.0_py312_qt6.rb
Formula/freecad@1.0.1_py312.rb
Formula/opencascade@7.5.3.rb
casks/freecad.rb
patches/freecad-0.20.1-py3.11-support.patch

This PR updates references to the
old FreeCAD site with new ones.
FYI, domains don't mind the casing.

FreeCADWeb.Org ➞ FreeCAD.Org

---

patches/freecad@1.0.2_py312-fix-with-pcl-v1.15.patch

```shell
```
```
```
```shell
```
--- …

[no ci] checkin patch to fix build with newer pcl versions ie. v1.13 and newer
